### ISSUE TITLE
Unable to use the code

### ISSUE THREAD

**Issue by He15ndy** [ammarsys/riot-password-changer#3]
Hello there, I'm trying to use the code but it doesn't work, I'm not sure what's the problem is
![image](https://github.com/ammarsys/riot-password-changer/assets/71564798/4316c4f1-0b40-43d9-8424-e7eef00ed9b7)

![image](https://github.com/ammarsys/riot-password-changer/assets/71564798/a2c55c84-276c-4918-a561-61688dc5fa95)

**Comment by ammarsys** [comment]
Hi there! Could you provide the entire traceback?

Also your OS and Python version.

**Comment by He15ndy** [comment]
I'm using Python 3.11 on windows 10
> INFO] Proces zapocet za Xievinerosr
> [INFO] Stara sifra je fahdawy011
> [INFO] Nova sifra je am8ftU5DxRn1XlYNopB7
> Traceback (most recent call last):
>   File "C:\Users\Hendy\Downloads\riot-password-changer-main\riot-password-changer-main\main.py", line 46, in <module>
>     change_account_password(username, password, new_password, sleep_time=2)
>   File "C:\Users\Hendy\Downloads\riot-password-changer-main\riot-password-changer-main\extended\utils.py", line 45, in change_account_password
>     driver = uc.Chrome(version_main=109)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Hendy\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 453, in __init__
>     super(Chrome, self).__init__(
>   File "C:\Users\Hendy\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 80, in __init__
>     super().__init__(
>   File "C:\Users\Hendy\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 104, in __init__
>     super().__init__(
>   File "C:\Users\Hendy\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 286, in __init__
>     self.start_session(capabilities, browser_profile)
>   File "C:\Users\Hendy\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 716, in start_session
>     super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
>   File "C:\Users\Hendy\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 378, in start_session
>     response = self.execute(Command.NEW_SESSION, parameters)
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Hendy\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 440, in execute
>     self.error_handler.check_response(response)
>   File "C:\Users\Hendy\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response
>     raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:59035
> from session not created: This version of ChromeDriver only supports Chrome version 109
> Current browser version is 114.0.5735.110
> Stacktrace:
> Backtrace:
>         (No symbol) [0x00A96643]
>         (No symbol) [0x00A2BE21]
>         (No symbol) [0x0092DA9D]
>         (No symbol) [0x00952911]
>         (No symbol) [0x0094A9D4]
>         (No symbol) [0x0094A7B1]
>         (No symbol) [0x00986917]
>         (No symbol) [0x0098655C]
>         (No symbol) [0x0097FB76]
>         (No symbol) [0x009549C1]
>         (No symbol) [0x00955E5D]
>         GetHandleVerifier [0x00D0A142+2497106]
>         GetHandleVerifier [0x00D385D3+2686691]
>         GetHandleVerifier [0x00D3BB9C+2700460]
>         GetHandleVerifier [0x00B43B10+635936]
>         (No symbol) [0x00A34A1F]
>         (No symbol) [0x00A3A418]
>         (No symbol) [0x00A3A505]
>         (No symbol) [0x00A4508B]
>         BaseThreadInitThunk [0x774500C9+25]
>         RtlGetAppContainerNamedObjectPath [0x77787B4E+286]
>         RtlGetAppContainerNamedObjectPath [0x77787B1E+238]
> 
> Exception ignored in: <function Chrome.__del__ at 0x000002CBAAF50A40>
> Traceback (most recent call last):
>   File "C:\Users\Hendy\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 800, in __del__
>   File "C:\Users\Hendy\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 755, in quit
> OSError: [WinError 6] The handle is invalid

**Comment by He15ndy** [comment]
I'm using Python 3.11 on windows 10

INFO] Proces zapocet za user
[INFO] Stara sifra je pass
[INFO] Nova sifra je am8ftU5DxRn1XlYNopB7
Traceback (most recent call last):
File "C:\Users\Hendy\Downloads\riot-password-changer-main\riot-password-changer-main\main.py", line 46, in
change_account_password(username, password, new_password, sleep_time=2)
File "C:\Users\Hendy\Downloads\riot-password-changer-main\riot-password-changer-main\extended\utils.py", line 45, in change_account_password
driver = uc.Chrome(version_main=109)
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Hendy\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver_init_.py", line 453, in init
super(Chrome, self).init(
File "C:\Users\Hendy\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 80, in init
super().init(
File "C:\Users\Hendy\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 104, in init
super().init(
File "C:\Users\Hendy\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 286, in init
self.start_session(capabilities, browser_profile)
File "C:\Users\Hendy\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver_init_.py", line 716, in start_session
super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
File "C:\Users\Hendy\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 378, in start_session
response = self.execute(Command.NEW_SESSION, parameters)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Hendy\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 440, in execute
self.error_handler.check_response(response)
File "C:\Users\Hendy\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response
raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:59035
from session not created: This version of ChromeDriver only supports Chrome version 109
Current browser version is 114.0.5735.110
Stacktrace:
Backtrace:
(No symbol) [0x00A96643]
(No symbol) [0x00A2BE21]
(No symbol) [0x0092DA9D]
(No symbol) [0x00952911]
(No symbol) [0x0094A9D4]
(No symbol) [0x0094A7B1]
(No symbol) [0x00986917]
(No symbol) [0x0098655C]
(No symbol) [0x0097FB76]
(No symbol) [0x009549C1]
(No symbol) [0x00955E5D]
GetHandleVerifier [0x00D0A142+2497106]
GetHandleVerifier [0x00D385D3+2686691]
GetHandleVerifier [0x00D3BB9C+2700460]
GetHandleVerifier [0x00B43B10+635936]
(No symbol) [0x00A34A1F]
(No symbol) [0x00A3A418]
(No symbol) [0x00A3A505]
(No symbol) [0x00A4508B]
BaseThreadInitThunk [0x774500C9+25]
RtlGetAppContainerNamedObjectPath [0x77787B4E+286]
RtlGetAppContainerNamedObjectPath [0x77787B1E+238]

Exception ignored in: <function Chrome.del at 0x000002CBAAF50A40>
Traceback (most recent call last):
File "C:\Users\Hendy\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver_init_.py", line 800, in del
File "C:\Users\Hendy\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver_init_.py", line 755, in quit
OSError: [WinError 6] The handle is invalid

**Comment by ammarsys** [comment]
Thanks for providing the entire traceback.

I will update the repository to fix this error soon.

**Comment by He15ndy** [comment]
Thank you so much, also please if you could add an option to change to a custom password because I'm so much of a noob with python, thanks again for your work 💖

**Comment by ammarsys** [comment]
I will most likely add it since it has been requested before.

Nonetheless, I will keep you updated.

Have a lovely evening.

**Comment by ammarsys** [comment]
Okay, I've gone ahead and pushed an update. I was not able to replicate the error but I made it so that it automatically detects the chrome version.

Can you do the following:

1. Update your Google Chrome version
2. Update the codebase
3. Run `RUN_ME.bat`

Also, I've translated the instructions to English and added a new feature (specific password). Please let me know if it works!

**Comment by He15ndy** [comment]
change_account_password(username, password, new_password, sleep_time=2)
  File "C:\Users\Hendy\Downloads\riot-password-changer-main (1)\riot-password-changer-main\extended\utils.py", line 54, in change_account_password
    driver = uc.Chrome()
             ^^^^^^^^^^^
  File "C:\Users\Hendy\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 453, in __init__
    super(Chrome, self).__init__(
  File "C:\Users\Hendy\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 80, in __init__
    super().__init__(
  File "C:\Users\Hendy\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 104, in __init__
    super().__init__(
  File "C:\Users\Hendy\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 286, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\Hendy\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 716, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "C:\Users\Hendy\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 378, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hendy\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Hendy\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:59168
from session not created: This version of ChromeDriver only supports Chrome version 109
Current browser version is 114.0.5735.110
Stacktrace:
Backtrace:
        (No symbol) [0x00956643]
        (No symbol) [0x008EBE21]
        (No symbol) [0x007EDA9D]
        (No symbol) [0x00812911]
        (No symbol) [0x0080A9D4]
        (No symbol) [0x0080A7B1]
        (No symbol) [0x00846917]
        (No symbol) [0x0084655C]
        (No symbol) [0x0083FB76]
        (No symbol) [0x008149C1]
        (No symbol) [0x00815E5D]
        GetHandleVerifier [0x00BCA142+2497106]
        GetHandleVerifier [0x00BF85D3+2686691]
        GetHandleVerifier [0x00BFBB9C+2700460]
        GetHandleVerifier [0x00A03B10+635936]
        (No symbol) [0x008F4A1F]
        (No symbol) [0x008FA418]
        (No symbol) [0x008FA505]
        (No symbol) [0x0090508B]
        BaseThreadInitThunk [0x774500C9+25]
        RtlGetAppContainerNamedObjectPath [0x77787B4E+286]
        RtlGetAppContainerNamedObjectPath [0x77787B1E+238]

Exception ignored in: <function Chrome.__del__ at 0x0000028F0DF239C0>
Traceback (most recent call last):
  File "C:\Users\Hendy\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 800, in __del__
  File "C:\Users\Hendy\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 755, in quit
OSError: [WinError 6] The handle is invalid

**Comment by ammarsys** [comment]
I've gone ahead and pushed an update again. It seems as if `undetected_chromedriver` (technology this program is using) fails to update the webdriver binary in some cases. In instance, mine was over a month old.

In the projects repository you'll find a `DELETE_OLD_BINARY.py` file. You can run it for it automatically to delete the file or just navigate to:

`C:\Users\Hendy\AppData\Roaming\undetected_chromedriver`

and delete the single `.exe` found in there.

Let me know if it works!

**Comment by He15ndy** [comment]
It's working perfectly fine, thank you so much for all the hard work <3
