### ISSUE TITLE
Issue on running the code

### ISSUE THREAD

**Issue by GusadeTaruna** [ammarsys/riot-password-changer#5]
Hello everyone, i found an issue when i try to using this code. I already implemented some of the solutions on the closed issue but still doesnt work. Appreciate the help. Below is the error attachment and detail
![image](https://github.com/ammarsys/riot-password-changer/assets/38973744/0cf0b9c5-9af1-4a30-9835-783be0e64d02)

Traceback (most recent call last):
  File "D:\Gusade\Coba-coba\riot-password-changer\main.py", line 52, in <module>
    change_account_password(username, password, new_password, sleep_time=2)
  File "D:\Gusade\Coba-coba\riot-password-changer\extended\utils.py", line 69, in change_account_password
    driver.find_element(By.XPATH, SIGN_IN_PAGE_LOGIN_BUTTON).click()
  File "C:\Users\Kad\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webelement.py", line 93, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\Kad\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webelement.py", line 403, in _execute
    return self._parent.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kad\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Kad\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <button type="submit" class="mobile-button mobile-button__submit" data-testid="btn-signin-submit" title="Sign In"></button> is not clickable at point (951, 760). Other element would receive the click: <div class="notification-overlay notification-overlay--animate">...</div>
  (Session info: chrome=114.0.5735.134)
Stacktrace:
Backtrace:
        GetHandleVerifier [0x00EDA813+48355]
        (No symbol) [0x00E6C4B1]
        (No symbol) [0x00D75358]
        (No symbol) [0x00DA5062]
        (No symbol) [0x00DA3B98]
        (No symbol) [0x00DA239B]
        (No symbol) [0x00DA179E]
        (No symbol) [0x00D99F5C]
        (No symbol) [0x00DBA73C]
        (No symbol) [0x00D99A36]
        (No symbol) [0x00DBAA94]
        (No symbol) [0x00DCC922]
        (No symbol) [0x00DBA536]
        (No symbol) [0x00D982DC]
        (No symbol) [0x00D993DD]
        GetHandleVerifier [0x0113AABD+2539405]
        GetHandleVerifier [0x0117A78F+2800735]
        GetHandleVerifier [0x0117456C+2775612]
        GetHandleVerifier [0x00F651E0+616112]
        (No symbol) [0x00E75F8C]
        (No symbol) [0x00E72328]
        (No symbol) [0x00E7240B]
        (No symbol) [0x00E64FF7]
        BaseThreadInitThunk [0x75297D59+25]
        RtlInitializeExceptionChain [0x7757B74B+107]
        RtlClearBits [0x7757B6CF+191]

Exception ignored in: <function Chrome.__del__ at 0x000001AEA64CE7A0>
Traceback (most recent call last):
  File "C:\Users\Kad\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 800, in __del__
  File "C:\Users\Kad\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 755, in quit
OSError: [WinError 6] The handle is invalid

**Comment by GusadeTaruna** [comment]
this is the chrome version im using
![image](https://github.com/ammarsys/riot-password-changer/assets/38973744/29c7d979-c7ee-46ad-b95b-ebc97a35b991)

**Comment by ammarsys** [comment]
sorry i didn't know that it would close the issue but yeah i pushed a fix, mind checking if it works?

**Comment by ammarsys** [comment]
Closed due to inactivity. Please reopen in case it does not work.

**Comment by Lejan0** [comment]
can i have your discord ?

**Comment by ammarsys** [comment]
@Lejan0 Hi, I can add you on Discord if you'd like. Just let me know what is your username and/or tag.

**Comment by Lejan0** [comment]
dis:ibleed
